# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](#260004)\
$directory\
[](fg:#260004 bg:#441116)\
$git_branch\
$git_status\
[](fg:#441116 bg:#692B39)\
$c\
$cpp\
$golang\
$gradle\
$java\
$nodejs\
$python\
[](fg:#692B39 bg:#22859B)\
$docker_context\
[](fg:#22859B bg:#00427B)\
$time\
[ ](fg:#00427B)
"""

add_newline = true

[os.symbols]
Alpine = " "
Android = " "
Arch = " "
Artix = " "
Debian = " "
Fedora = " "
Kali = " "
Linux = " "
Mint = " "
Pop = " "
Raspbian = " "
Redhat = " "
Ubuntu = " "
Unknown = " "
Windows = "󰍲 "

[directory]
style = "bg:#260004"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "/"

[directory.substitutions]

[docker_context]
symbol = " "
style = "bg:#22859B"
format = '[ $symbol $context ]($style)'

[git_branch]
symbol = ""
style = "bg:#441116"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#441116"
format = '[$all_status$ahead_behind ]($style)'

[c]
symbol = ""
style = "bg:#692B39"
format = '[ $symbol ($version) ]($style)'

[cpp]
symbol = ""
style = "bg:#692B39"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = ""
style = "bg:#692B39"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#692B39"
format = '[ $symbol ($version) ]($style)'

[python]
symbol = ""
style = "bg:#692B39"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%H:%M"
style = "bg:#00427B"
format = '[ $time ]($style)'
