#C03F60
#9A348F
#1b91d1
#33658B
#212954

format = """
[](#C03F60)\
$directory\
[](fg:#C03F60 bg:#9A348F)\
$git_branch\
$git_status\
[](fg:#9A348F bg:#1b91d1)\
$c\
$cpp\
$golang\
$gradle\
$java\
$nodejs\
$python\
[](fg:#1b91d1 bg:#33658B)\
$docker_context\
[](fg:#33658B bg:#212954)\
$time\
[ ](fg:#212954)\
"""

add_newline = true

[username]
show_always = true
style_user = "bg:#f04d27"
style_root = "bg:#f04d27"
format = '[$user ]($style)'
disabled = false

[os]
style = "bg:#f04d27"
disabled = false

[os.symbols]
Alpine = " "
Android = " "
Arch = " "
Artix = " "
Debian = " "
Fedora = " "
Kali = " "
Linux = " "
Mint = " "
Pop = " "
Raspbian = " "
Redhat = " "
Ubuntu = " "
Unknown = " "
Windows = "󰍲 "

[directory]
style = "bg:#C03F60"
format = "[ $path ]($style)"
truncation_length = 5
truncation_symbol = "/"

[directory.substitutions]
".config" = ". "

[docker_context]
symbol = " "
style = "bg:#33658B"
format = '[ $symbol $context ]($style)'

[git_branch]
symbol = ""
style = "bg:#9A348F"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#9A348F"
format = '[$all_status$ahead_behind ]($style)'

[c]
symbol = "c"
style = "bg:#1b91d1"
format = '[ $symbol ($version) ]($style)'

[cpp]
symbol = "c++"
style = "bg:#1b91d1"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = "java"
style = "bg:#1b91d1"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = "node"
style = "bg:#1b91d1"
format = '[ $symbol ($version) ]($style)'

[python]
symbol = "py"
style = "bg:#1b91d1"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%H:%M"
style = "bg:#212954"
format = '[ $time ]($style)'
