# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """
[]($COLOR0)\
$directory\
[](fg:$COLOR0 bg:$COLOR1)\
$git_branch\
$git_status\
[](fg:$COLOR1 bg:$COLOR2)\
$c\
$cpp\
$golang\
$gradle\
$java\
$nodejs\
$python\
[](fg:$COLOR2 bg:$COLOR3)\
$docker_context\
[](fg:$COLOR3 bg:$COLOR4)\
$time\
[ ](fg:$COLOR4)
"""

add_newline = true

[os.symbols]
Alpine = " "
Android = " "
Arch = " "
Artix = " "
Debian = " "
Fedora = " "
Kali = " "
Linux = " "
Mint = " "
Pop = " "
Raspbian = " "
Redhat = " "
Ubuntu = " "
Unknown = " "
Windows = "󰍲 "

[directory]
style = "bg:$COLOR0"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "/"

[directory.substitutions]

[docker_context]
symbol = " "
style = "bg:$COLOR3"
format = '[ $symbol $context ]($style)'

[git_branch]
symbol = ""
style = "bg:$COLOR1"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:$COLOR1"
format = '[$all_status$ahead_behind ]($style)'

[c]
symbol = ""
style = "bg:$COLOR2"
format = '[ $symbol ($version) ]($style)'

[cpp]
symbol = ""
style = "bg:$COLOR2"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = ""
style = "bg:$COLOR2"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:$COLOR2"
format = '[ $symbol ($version) ]($style)'

[python]
symbol = ""
style = "bg:$COLOR2"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%H:%M"
style = "bg:$COLOR4"
format = '[ $time ]($style)'
